### ISSUE TITLE
Seeking ideas to manage the different repos and versions so that it all works.

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/org#24]
We now have (at least) 4 core python libraries, which may have heavy dependencies on each other:
- bigchaindb (server)
- cryptoconditions
- bigchaindb-common
- bigchaindb-driver

And two higher level (~application) Python libraries:
- pycoalaip
- pycoalaip-bigchaindb

This issue seeks to outline a clear workflow/procedure to ensure that we can keep on having fast release cycles meanwhile preserving the functionalities and proper behaviours of each component.

Some key things that need to be handled:
- breaking changes in one or more libs
- keeping in mind that eventually (hopefully) there will be multiple clients out of our control, and consequently the BigchainDB Server HTTP API is a contract with clients.

**Comment by sohkai** [comment]
> Breaking changes in one or more libs

An advantage to having mono-repos; they test the entire project and all the other packages so a breaking change in one package will immediately fail another's tests.

Maybe we could set something up where we have nightly builds and tests of all the packages on travis?

-------

As for versioning, I've usually set it to a hard version number on release and then moved everything back to using the master branch for development. Maybe different requirements files or etc. for dev and release would help here?

**Comment by ttmc** [comment]
For the record, Brett and Sylvain had a meeting to discuss the options and they put together a Google doc summarizing them.

The first action was to merge (most of) the bigchaindb-common repo back into the bigchaindb repo. See https://github.com/bigchaindb/bigchaindb/issues/706 and https://github.com/bigchaindb/bigchaindb/pull/742

In the future, we may also merge the Python driver repo (bigchaindb-driver) into the bigchaindb repo, but in its own subdirectory.

**Comment by sbellem** [comment]
One idea to help manage the different (Python) repos and versions, and especially when a repo is under development, and some other repo is dependent on the dev version of it:

Rather than increasing the version in setup.py at the very end, just before releasing, update setup.py at the very beginning, once master starts to have new code that the latest release on PyPI does not have.

Doing so may allow us to more easily use the `dependency_links` option of `setup`.

**Comment by ttmc** [comment]
@sbellem That's a nice idea. A variation:

* Right after releasing, update the version label to `release version number + 0.1` and append a `dev` to that. For example: After releasing `0.7.0`, update the version in the master branch to `0.8.0dev`. I wonder if that would work with ReadTheDocs, setuptools, etc.

* Right before releasing, remove the `dev` from the end of the version label.

**Comment by sbellem** [comment]
@ttmc yes! I had actually thought of that, but did not put it now, to keep the idea simple. Eventually, we could cycle through `dev`, `alpha`, `rc1`, `rc2`, etc.

**Comment by sohkai** [comment]
@ttmc I think that's also the best way. Appending `next ver + dev` immediately after release and then removing it on the next release is probably the most clear way of expressing our intent on the versions.

**Comment by sbellem** [comment]
> I wonder if that would work with ReadTheDocs, setuptools, etc.

I also wonder. The `.dev` may complicate things.

**Comment by sbellem** [comment]
well, what I feared: https://readthedocs.org/projects/bigchaindb-python-driver/builds/4572546/

**Comment by sbellem** [comment]
ok, that works: https://readthedocs.org/projects/bigchaindb-python-driver/builds/4572559/

**Comment by ttmc** [comment]
@sbellem Can you elaborate? The driver docs build you pointed to has version = `0.0.2.dev12`. I guess part of the trick is to put a dot before the `dev`?

**Comment by sbellem** [comment]
##### Summary 

* with bigchaindb version set to 0.7.0.dev: https://github.com/sbellem/bigchaindb/tree/0.7.0.dev
* with the driver pointing to 0.7.0.dev in [setup.py](https://github.com/bigchaindb/bigchaindb-driver/blob/dev/setup.py#L14) and using [dependency_links](https://github.com/bigchaindb/bigchaindb-driver/blob/dev/setup.py#L41-L43) 

it seems to work when running `python setup.py install`

If we do not have a version specified in `setup.py`, the command `python setup.py install` fails, as in https://readthedocs.org/projects/bigchaindb-python-driver/builds/4569421/

**Comment by sbellem** [comment]
> The driver docs build you pointed to has version = 0.0.2.dev12. I guess part of the trick is to put a dot before the dev?

Oh, I was referring to the version of `bigchaindb`
