### ISSUE TITLE
Documentation: Who is our audience?

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/org#25]
The purpose of this issue is the address the question as stated in the title: Who is our audience?

Moreover, what knowledge do we assume our audience has. Example: do they need to be told how to install Python, pip?

This question was raised in PR https://github.com/bigchaindb/bigchaindb-driver/pull/138 as some think that we are documenting too many things, and burying the essentials under too many details, which makes it more time consuming for the average developer to simply find what they need.

**Comment by vrde** [comment]
The discussion started form this PR: https://github.com/bigchaindb/bigchaindb-driver/pull/138.

**Comment by ttmc** [comment]
The question should really be, "Who is the audience for the Python Driver docs today?" because that was the context where it came up.

Today, we only have one driver: the Python driver. That means that the only way for a developer to play with an existing driver is to use the Python driver, even if they're not a Python developer. Therefore, I assumed that the audience could _range_ from a non-Python developer (e.g. a Java developer) to a seasoned Python developer.

In the future, when there are hundreds of different drivers (including for COBOL and Battlestar), we'll no longer have to assume that the reader might be a non-Python developer.

**Comment by sbellem** [comment]
Yes, sure, but still. the docs are simply no longer well suited for simple ordinary engineers, devs, sys admins, who know Python. And this is very upsetting.

That is why I had proposed a section "New to Python".

Quickstart should be a quickstart. And right now, depending on who you are, it may not be at all. If you know Python and work on Mac OS X like many do, and go to quickstart, you are out of luck. 

In the Python world, a quickstart is `pip install <package_name>` and if they are `C` dependencies, or what not, then yes, they can be mentioned before or after. But that is pretty much it. 

Any how, that is my opinion, and I am just expressing it here.

**Comment by ttmc** [comment]
Sometimes I go to one of those so-called "Quickstart" pages and it starts out with `npm this` or `rpm that` or `cargo fishsticks` or `brew potion` or whatever. I end up leaving the page, switching context, figuring out how to install the snazzy package manager... It's not "quick" for me.

I'd like to add a Quickstart for Mac users but I don't have any way to test it.

In my opinion, a Quickstart should just be a bunch of stuff that you can just copy & paste to get going and it should just work. If it adds a bunch of cruft to their system, then that's their problem. If they want something specially tailored to them, then they should go to the Advanced Installation page and do what makes sense for them.

**Comment by sbellem** [comment]
The main point I wish to bring across here is that we are ignoring an audience which I think is important. This audience knows how to use Python, and does not need to be told much except for what the package name to install is, plus header files if that applies. This audience is ignored because neither the quickstart nor the advanced installation give the essential in a straight forward manner, which is:

```python
pip install <package_name>
```

This information is especially important in the case of a package like `bigchaindb_driver` since the github repo is named differently: `bigchaindb-driver`, and someone could mistakenly try to install it via 

```bash
pip install bigchaindb-driver
```

instead of

```bash
pip install bigchaindb_driver
```

**Comment by sbellem** [comment]
To repeat again, in a different way, I think we should not sacrifice an audience at the expense of another one.

**Comment by ttmc** [comment]
What are you suggesting? Should the Python Driver Quickstart page be something like below? If it's not what you have in mind, then please show me what you have in mind.

<hr>

# Quickstart

Options:

- If you have `ffi.h` installed and are using Python 3 (including Python 3 versions of `pip` and `setuptools`), then do `pip install bigchaindb_driver` and go to the **Basic Usage Examples**.
- If you'd like to copy and paste some commands that will install the BigchainDB Python Driver and everything needed to run it, see the **Installation Recipes** for various operating systems.
- **Advanced Installation**

**Comment by sbellem** [comment]
First, I think one Installation page is enough.

The dependencies on Python 3.5+ and `libffi/ffi.h` can be mentioned briefly at the beginning, after which the command to install the driver can be given:

```bash
pip install bigchaindb_driver
```

Following the above, there could be a section about "Installing Dependencies". The most important dependency to cover is `ffi.h` after which Python 3, pip, and so forth could be covered.

The reasoning behind the proposed approach is that it quickly serves the users who already know the Python ecosystem, meanwhile still serving those who need more help.

Furthermore, someone who is new to a technology, will very often already be in a "search and learn" mode, and therefore I think it is okay that they need to read, and scroll a bit more. On the other hand someone who knows their way around simply needs clear, precise pointers, and they very often do not want to bother with beginner's instructions.

Lastly, I think it would be good to look at other similar projects to see how they approach this part of the docs. Some examples:

* [rethinkdb](https://www.rethinkdb.com/docs/install-drivers/python/)
* [pymongodb](https://api.mongodb.com/python/current/installation.html)
* [asyncpg](https://magicstack.github.io/asyncpg/current/index.html)
* [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/index.html)

As an aside: regarding dependencies: see issues https://github.com/bigchaindb/bigchaindb-driver/issues/139 and https://github.com/bigchaindb/bigchaindb-driver/issues/140.

**Comment by ttmc** [comment]
Okay, I will try again, but I'm getting extremely frustrated because I'm just being given vague general ideas, all good, and all in conflict with each other.

**Comment by libscott** [comment]
+1 for using `pip3` over regular `pip`. I've been using Python for a while but if I saw `pip install bigchaindb_driver` I'd probably chuck it in the terminal before reading the small print.

**Comment by sbellem** [comment]
No, simply no. There are multiple possibilities, in which `pip` will do just fine. It is the responsibility of the developer to figure that out as it will depend on their underlying system, and other factors.
