### ISSUE TITLE
WOTN : 500 Internal Server Error with non ascribe.io picture url

### ISSUE THREAD

**Issue by eldk** [bigchaindb/org#29]
Hello,

I'm testing ascribe.io + whereonthe.net .

While checking one picture with original url from my website , I get :  

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">`
`<title>500 Internal Server Error</title>`
`<h1>Internal Server Error</h1>`
`<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>`

Whereas checking the same picture, but, with https://xxxx.cloudfront.net/live/yyyy/digitalwork/zzzz.jpg url picked on ascribe.io, I've got a 200 response with results.

I have tested with pictures randomly picked on the web, some gives 200, others 500 or 502 responses.

Any help ?

Thanks,

Eric

**Comment by vrde** [comment]
Hi @eldk, thanks for reporting the bug! It should be fixed now. I just followed up with an email.
