### ISSUE TITLE
CC FR Project login vs www.ascribe.io login : Licence selector not displayed

### ISSUE THREAD

**Issue by eldk** [bigchaindb/org#30]
Hello,

When login through :  https://cc.ascribe.io/?lang=fr
license (Creative Common) should be selected.
Whereas login through : https://www.ascribe.io/app/login
no license selector is displayed.

It's a bit confusing.

Work registered through https://www.ascribe.io/app/login : https://www.ascribe.io/app/pieces/27232
Then deleted (No license in the workflow - or I've missed something).
And then registered through https://cc.ascribe.io/?lang=fr and licensed : https://www.ascribe.io/app/pieces/27233 .

Thanks,

Eric

**Comment by TimDaub** [comment]
@eldk Thanks for reporting this bug. It's actually fixed since a while.

**Comment by eldk** [comment]
Thanks.
