### ISSUE TITLE
Internal server error - 0.9.3 - MongoDB

### ISSUE THREAD

**Issue by Dsouza10082** [bigchaindb/org#33]
Hi!

I facing "Internal server error" when i try to CREATE or GET details over transactionID. My transaction templace is fine, i try to first use the BigchainDB example to test if the error is my CREATE request, but when i try occurs the same...
My version is 0.9.3 with MongoDB 3.4, all starts fine, the access is unblocked to try.
http://node-koinplace-southeast-16866.cloudapp.net:9983/api/v1
 
Thanks !

**Comment by ttmc** [comment]
@Dsouza10082 This repository is mainly for high-level planning; could you copy this issue to the main BigchainDB Server (code) repository at https://github.com/bigchaindb/bigchaindb/issues 

I wonder why you are using port 9983; we usually use port 9984 for BigchainDB Server.

Also, please add:

* The server operating system where BigchainDB and MongoDB are running, including the OS version
* Your local operating system
* The version of Python on the server and on your local machine: `$ python --version`
* How are you building BigchainDB transactions? Are you using the BigchainDB Python Driver, and if so, which version?
* The exact steps you did, so we can reproduce your error

**Comment by Dsouza10082** [comment]
Hi @ttmc !

The 9983 is a mistake made by me ;) 
In production environment i fix that.

    **The server operating system where BigchainDB and MongoDB are running, including the OS version
    Your local operating system**

     BigchainDB(0.9.3) and MongoDB(3.4) are runing on Azure VMS classic(Ubuntu 16.04 LTS)

     My local operation System is Windows 10
    
    **The version of Python on the server and on your local machine: $ python --version**
 
    Python 2.7.12 and Python 3.5.2
  
    **How are you building BigchainDB transactions? Are you using the BigchainDB Python Driver, and if so, which version?**

I work with sohkai quickStart,  made in Node.js and works very well, all the flow are ok, at the point i know.

**Comment by ttmc** [comment]
@Dsouza10082 Could you try switching from Python 2.7.12 to Python 3.5.x on the server? BigchainDB Server is _Python 3 only_; I'm a bit amazed you got it to run on Python 2.7.12. We only test it on Python 3.4 and Python 3.5.

**Comment by Dsouza10082** [comment]
@ttmc  first of all thanks! Did work now !

What i did:

Remove all python 2.7 data, Ubuntu 16.04 LTS is python 3.x by default, so i change the python3 alias to python.

sudo alias python=/usr/bin/python3 

And restart the server.

Thank you for the tips !
