### ISSUE TITLE
IPDB production net usable by vetted third parties

### ISSUE THREAD

**Issue by wrigley** [bigchaindb/org#4]
# Abstract

IPDB live net usable by vetted third parties
# Motivation

foo
# Goals
- foo goal 1
- foo goal 2
# Challenges

Foo
- foo challenge 1?
- foo challenge 2?
# Architecture

foo
## Examples

foo
# Tasks

**Friday, foo date 1:**
- [ ] foo task 1
- [ ] foo task 2

**Friday, foo date 2:**
- [ ] foo task 3
- [ ] foo task 4

**Comment by ttmc** [comment]
We're reframing how we think about the IPDB rollout, so I'm closing this issue.
