### ISSUE TITLE
IPDB test net usable by vetted 3rd parties

### ISSUE THREAD

**Issue by wrigley** [bigchaindb/org#5]
# Abstract

IPDB test net usable by vetted 3rd parties

**Comment by ttmc** [comment]
This project is basically done. All that really needs to happen is for someone to [run the AWS deployment scripts](https://bigchaindb.readthedocs.io/en/latest/clusters-feds/aws-testing-cluster.html). The only reason that hasn't happened yet is that AWS isn't free, and there was no point in racking up expenses needlessly.

**Comment by sohkai** [comment]
@ttmc Should we close this?

**Comment by ttmc** [comment]
@sohkai Thanks for asking. Yes, I think it would be accurate to close this issue now.
