### ISSUE TITLE
Internal production network (cluster)

### ISSUE THREAD

**Issue by wrigley** [bigchaindb/org#6]
# Abstract

Issue #310 was the prototype; this ticket takes it to production. This includes the need for an IPDB live net (vs. just test net).
# Motivation

WIP
# Goals

WIP
- foo goal 1
- foo goal 2
# Challenges

WIP
- foo challenge 1?
- foo challenge 2?
# Architecture

WIP
## Examples

WIP
# Tasks

**Friday, foo date 1:**
- [ ] foo task 1
- [ ] foo task 2

**Friday, foo date 2:**
- [ ] foo task 3
- [ ] foo task 4

**Comment by ttmc** [comment]
We're reframing how we think about the IPDB rollout, so I'm closing this issue.
