### ISSUE TITLE
Open source 3D-match

### ISSUE THREAD

**Issue by wrigley** [bigchaindb/org#8]
Umbrella issue for all tasks related to open-sourcing 3D match. 

- [x] Review current state of code

- [x] ??

etc.

**Comment by wrigley** [comment]
@rhsimplex Maybe flesh out the description more, and post a link to the final, open-source code.

**Comment by ttmc** [comment]
This issue now resolved, more or less, so I'll close it. The final open-source code is at:

https://github.com/ascribe/match3d

**Comment by ttmc** [comment]
From @sbellem 

github: https://github.com/ascribe/match3d
pypi: https://pypi.python.org/pypi/match3d
rtd: https://match3d.readthedocs.io/en/latest/
